### ISSUE TITLE
What does "write better" mean?

### ISSUE THREAD

**Issue by chmac** [SeriousBug/writing-assistant#8]
Maybe you could add something to the readme that gives a bit of context? From reading #4 I guess it's about flagging certain types of words, or grammar analysis, or something like that. But I definitely couldn't figure that out from the readem. :-)

**Comment by SeriousBug** [comment]
So this extension ended up falling quite short of what I had planned for it at first. I was thinking of basically Grammarly but open source and in your editor, but what it does is quite a bit more limited:
- It can warn you about profanities/swear words
- Warns about unnecessary acronyms (like PIN Number)
- Warns if the reading level of the text is too high

The dependencies it uses to do these are honestly not that amazing though, they are all pretty simple. I have some plans to design some machine-learning algorithm that can understand good writing and offer suggestions for you... but I've been sidetracked by other projects at the moment (mostly messing around with rust right now). I'll eventually come back and improve this extension at some point.

**Comment by SeriousBug** [comment]
And just to clarify since we previously interacted on Dendron, this project is completely independent and has nothing to do with Dendron. I develop it on my free time, and Dendron does not support or recommend this extension.

**Comment by chmac** [comment]
Yeah, I understood it's a side project! Opened a PR.
